### ISSUE TITLE
testWriteMap fails when run in a different TZ

### ISSUE THREAD

**Issue by delocalizer** [Complexible/pinto#24]
running `gradle build`:
```
com.complexible.pinto.RDFMapperTests > testWriteMap FAILED
    java.lang.AssertionError at RDFMapperTests.java:740
```

Turns out this is because `Models.isomorphic` doesn't consider the same instant at different timezones to be equal:
My local TZ is UTC+10:00. 
The `assertTrue` isomorphism comparison at [RDFMapperTests.java#L740](https://github.com/stardog-union/pinto/blob/develop/test/src/com/complexible/pinto/RDFMapperTests.java#L740) fails because the date as constructed from the Long at [RDFMapperTests.java#L732](https://github.com/stardog-union/pinto/blob/develop/test/src/com/complexible/pinto/RDFMapperTests.java#L732) becomes:
`"2015-03-15T05:24:42.470+10:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>`
which is different than the reference value from `data/map.nt` of:
`"2015-03-14T15:24:42.470-04:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>`

If I change the date in `data/map.nt` to be `"2015-03-15T05:24:42.470+10:00"^^<http://www.w3.org/2001/XMLSchema#dateTime>`, the test passes.

**Comment by mhgrove** [comment]
sounds like Models.isomorphic could use a fix, but we could do more to help avoid their shortcoming?
